// <auto-generated />
namespace QLKSProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<< HEAD:QLKSProject/QLKSProject/Migrations/202006290812118_g.Designer.cs
    public sealed partial class g : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(g));
        
        string IMigrationMetadata.Id
        {
            get { return "202006290812118_g"; }
=======
    public sealed partial class createDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202006291006510_createDB"; }
>>>>>>> b4de312ef247bbb90f834c12e3bdad425a1fda8b:QLKSProject/QLKSProject/Migrations/202006291006510_createDB.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
